### ISSUE TITLE
TODO - 2025

### ISSUE THREAD

**Issue by HeloiseS** [genghisken/psat-server-web#39]
- Clean up the names of the API serialisers urls etc..
- use get and post properly 
- TESTS (api stuff)
- sing up page
- integrate read only permissions to the web interface so people don\t click on the wrong button by accident

**Comment by HeloiseS** [comment]
### Post JOSS submission update

#### Done
- [x] Integrate read only permissions to the web interface

#### 🦀  **Priority**
- [ ] **[ALL]** Add a “Create User” form (only accessible by admins) under the name.surname header on the webpage where we can
   - [ ]  Chose how long API token valid for (tick boxes to select Group)
   - [ ] Tick box to provide write access to web server (if relevant) 
   - [ ]  automatically sets the ``password_unusable_fl =True`` so don’t have to tick a box like in the Admin interface
   - [ ] Add a “Profile” by stealing the [profile model django code from Lasair ](https://github.com/lsst-uk/lasair-lsst/blob/main/webserver/users/models.py)
       - [ ] Make default spaghetti monster or crab
- [ ]  [@jackleland] Fix the width of the privacy policy 
- [ ]   [@jackleland]  Fix the footer so it doesn’t hover
- [ ] [@genghisken] Upgrade Django to 5.2 

####  🐧 **Priority** 
- [ ] Clean up the names of the API endpoints
- [ ]  Give automatic write access to webserver to group members with API write access. 

- [ ]  Refactor the atlas views into the accounts views


#### 🐌  **Priority** 
- [ ] Review our use of GET and POST  
   - [ ] Assess what will break in production 
   - [ ] Is it worht the effort?

####  🛑  Retired
- **Sign-up page**: Decided against it instead added a data access request form
